// npm-packages/private-demos/quickstarts/vue/src/App.vue
<script setup lang="ts">
import { useConvexQuery } from "convex-vue";
import { api } from "../convex/_generated/api";

const { data, isPending } = useConvexQuery(api.tasks.get);
</script>

<template>
  <span v-if="isPending"> Loading... </span>
  <ul v-else>
    <li v-for="todo in data">
      {{ todo.text }} {{ todo.isCompleted ? "☑" : "☐" }}
    </li>
  </ul>
</template>

// npm-packages/private-demos/quickstarts/react-vite-ts/src/App.tsx
import "./App.css";
import { useQuery } from "convex/react";
import { api } from "../convex/_generated/api";

function App() {
  const tasks = useQuery(api.tasks.get);
  return (
    <div className="App">
      {tasks?.map(({ _id, text }) => <div key={_id}>{text}</div>)}
    </div>
  );
}

export default App;
