// npm-packages/private-demos/quickstarts/nuxt/app.vue
<script setup lang="ts">
import { api } from "@/convex/_generated/api";

const { data: tasks } = useConvexQuery(api.tasks.get);
</script>

<template>
  <div>
    <h1>Tasks</h1>
    <ul v-if="tasks">
      <li v-for="task in tasks" :key="task._id">
        <input :id="task._id" type="checkbox" :checked="task.isCompleted" />
        <label :for="task._id">{{ task.text }}</label>
      </li>
    </ul>
  </div>
</template>

// npm-packages/private-demos/quickstarts/react-vite-ts/src/App.tsx
import "./App.css";
import { useQuery } from "convex/react";
import { api } from "../convex/_generated/api";

function App() {
  const tasks = useQuery(api.tasks.get);
  return (
    <div className="App">
      {tasks?.map(({ _id, text }) => <div key={_id}>{text}</div>)}
    </div>
  );
}

export default App;
